package net.synqg.qg.cleaners;

import net.synqg.qg.service.GeneratedQuestion;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

/**
 * Filters out discourse words since questions won't have any context here.
 *
 * @author kaustubhdholé.
 */
public class DiscourseWordsCleaner implements QuestionCleaner {

    private static final List<String> discourseWords = Arrays.asList("therefore", "hence", "since",
            "thereafter", "furthermore", "moreover", "henceforth");

    @Override
    public Map<GeneratedQuestion, String> apply(Map<GeneratedQuestion, String> questionAnswerPairs) {
        for (GeneratedQuestion autoGeneratedQuestion : questionAnswerPairs.keySet()) {
            String answer = questionAnswerPairs.get(autoGeneratedQuestion);
            for (String reasonWord : discourseWords) {
                if (answer.toLowerCase().startsWith(reasonWord)) {
                    questionAnswerPairs.put(autoGeneratedQuestion, answer.split(" ", 2)[1]);
                }
            }
        }
        return questionAnswerPairs;
    }
}
